# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    vendor/htc/m8qlul/proprietary/app/EasyAccessService.apk:system/app/EasyAccessService.apk \
    vendor/htc/m8qlul/proprietary/app/TimeService.apk:system/app/TimeService.apk \
    vendor/htc/m8qlul/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/htc/m8qlul/proprietary/bin/adsprpcd:system/bin/adsprpcd_vendor \
    vendor/htc/m8qlul/proprietary/bin/audiod:system/bin/audiod_vendor \
    vendor/htc/m8qlul/proprietary/bin/cand:system/bin/cand \
    vendor/htc/m8qlul/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/htc/m8qlul/proprietary/bin/hcheck-v2:system/bin/hcheck-v2 \
    vendor/htc/m8qlul/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/htc/m8qlul/proprietary/bin/htc_ebdlogd:system/bin/htc_ebdlogd \
    vendor/htc/m8qlul/proprietary/bin/imscmservice:system/bin/imscmservice \
    vendor/htc/m8qlul/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/htc/m8qlul/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/htc/m8qlul/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/htc/m8qlul/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
    vendor/htc/m8qlul/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/htc/m8qlul/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
    vendor/htc/m8qlul/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/htc/m8qlul/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/htc/m8qlul/proprietary/bin/radish:system/bin/radish \
    vendor/htc/m8qlul/proprietary/bin/rild:system/bin/rild \
    vendor/htc/m8qlul/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/htc/m8qlul/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/htc/m8qlul/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/htc/m8qlul/proprietary/etc/RT5501:system/etc/RT5501 \
    vendor/htc/m8qlul/proprietary/etc/acdbdata/MTP/Bluetooth_cal.acdb:system/etc/acdbdata/MTP/Bluetooth_cal.acdb \
    vendor/htc/m8qlul/proprietary/etc/acdbdata/MTP/General_cal.acdb:system/etc/acdbdata/MTP/General_cal.acdb \
    vendor/htc/m8qlul/proprietary/etc/acdbdata/MTP/Global_cal.acdb:system/etc/acdbdata/MTP/Global_cal.acdb \
    vendor/htc/m8qlul/proprietary/etc/acdbdata/MTP/Handset_cal.acdb:system/etc/acdbdata/MTP/Handset_cal.acdb \
    vendor/htc/m8qlul/proprietary/etc/acdbdata/MTP/Hdmi_cal.acdb:system/etc/acdbdata/MTP/Hdmi_cal.acdb \
    vendor/htc/m8qlul/proprietary/etc/acdbdata/MTP/Headset_cal.acdb:system/etc/acdbdata/MTP/Headset_cal.acdb \
    vendor/htc/m8qlul/proprietary/etc/acdbdata/MTP/Speaker_cal.acdb:system/etc/acdbdata/MTP/Speaker_cal.acdb \
    vendor/htc/m8qlul/proprietary/etc/acdbdata/MTP/Speaker_cal.acdb:system/etc/acdbdata/MTP/Speaker_cal.acdb \
    vendor/htc/m8qlul/proprietary/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/htc/m8qlul/proprietary/etc/firmware/ILP0100_IPM_Code_out.bin:system/etc/firmware/ILP0100_IPM_Code_out.bin \
    vendor/htc/m8qlul/proprietary/etc/firmware/ILP0100_IPM_Data_out.bin:system/etc/firmware/ILP0100_IPM_Data_out.bin \
    vendor/htc/m8qlul/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/alIAF_InData_4M2M:system/etc/firmware/alIAF_InData_4M2M \
    vendor/htc/m8qlul/proprietary/etc/firmware/cmnlib.b00:system/etc/firmware/cmnlib.b00 \
    vendor/htc/m8qlul/proprietary/etc/firmware/cmnlib.b01:system/etc/firmware/cmnlib.b01 \
    vendor/htc/m8qlul/proprietary/etc/firmware/cmnlib.b02:system/etc/firmware/cmnlib.b02 \
    vendor/htc/m8qlul/proprietary/etc/firmware/cmnlib.b03:system/etc/firmware/cmnlib.b03 \
    vendor/htc/m8qlul/proprietary/etc/firmware/cmnlib.mdt:system/etc/firmware/cmnlib.mdt \
    vendor/htc/m8qlul/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/dxhdcp2.b00:system/etc/firmware/dxhdcp2.b00 \
    vendor/htc/m8qlul/proprietary/etc/firmware/dxhdcp2.b01:system/etc/firmware/dxhdcp2.b01 \
    vendor/htc/m8qlul/proprietary/etc/firmware/dxhdcp2.b02:system/etc/firmware/dxhdcp2.b02 \
    vendor/htc/m8qlul/proprietary/etc/firmware/dxhdcp2.b03:system/etc/firmware/dxhdcp2.b03 \
    vendor/htc/m8qlul/proprietary/etc/firmware/dxhdcp2.mdt:system/etc/firmware/dxhdcp2.mdt \
    vendor/htc/m8qlul/proprietary/etc/firmware/hcheck.b00:system/etc/firmware/hcheck.b00 \
    vendor/htc/m8qlul/proprietary/etc/firmware/hcheck.b01:system/etc/firmware/hcheck.b01 \
    vendor/htc/m8qlul/proprietary/etc/firmware/hcheck.b02:system/etc/firmware/hcheck.b02 \
    vendor/htc/m8qlul/proprietary/etc/firmware/hcheck.b03:system/etc/firmware/hcheck.b03 \
    vendor/htc/m8qlul/proprietary/etc/firmware/hcheck.mdt:system/etc/firmware/hcheck.mdt \
    vendor/htc/m8qlul/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/htc/m8qlul/proprietary/etc/firmware/lscbuffer_rev2.bin:system/etc/firmware/lscbuffer_rev2.bin \
    vendor/htc/m8qlul/proprietary/etc/firmware/mirlink.b00:system/etc/firmware/mirlink.b00 \
    vendor/htc/m8qlul/proprietary/etc/firmware/mirlink.b01:system/etc/firmware/mirlink.b01 \
    vendor/htc/m8qlul/proprietary/etc/firmware/mirlink.b02:system/etc/firmware/mirlink.b02 \
    vendor/htc/m8qlul/proprietary/etc/firmware/mirlink.b03:system/etc/firmware/mirlink.b03 \
    vendor/htc/m8qlul/proprietary/etc/firmware/mirlink.mdt:system/etc/firmware/mirlink.mdt \
    vendor/htc/m8qlul/proprietary/etc/firmware/nfc_test.bin:system/etc/firmware/nfc_test.bin \
    vendor/htc/m8qlul/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/htc/m8qlul/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/htc/m8qlul/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/htc/m8qlul/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/htc/m8qlul/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/htc/m8qlul/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/htc/m8qlul/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/htc/m8qlul/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    vendor/htc/m8qlul/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    vendor/htc/m8qlul/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    vendor/htc/m8qlul/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03 \
    vendor/htc/m8qlul/proprietary/etc/firmware/widevine.mdt:system/etc/firmware/widevine.mdt \
    vendor/htc/m8qlul/proprietary/etc/hldm.bin:system/etc/hldm.bin \
    vendor/htc/m8qlul/proprietary/etc/hltof.bin:system/etc/hltof.bin \
    vendor/htc/m8qlul/proprietary/etc/hltrd.bin:system/etc/hltrd.bin \
    vendor/htc/m8qlul/proprietary/etc/sound_mfg.txt:system/etc/sound_mfg.txt \
    vendor/htc/m8qlul/proprietary/etc/tfa/Rec_Video.drc:system/etc/tfa/Rec_Video.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/Rec_Video.eq:system/etc/tfa/Rec_Video.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/Rec_Video.preset:system/etc/tfa/Rec_Video.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/Rec_Video_l.drc:system/etc/tfa/Rec_Video_l.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/Rec_Video_l.eq:system/etc/tfa/Rec_Video_l.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/Rec_Video_l.preset:system/etc/tfa/Rec_Video_l.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/fm.drc:system/etc/tfa/fm.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/fm.eq:system/etc/tfa/fm.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/fm.preset:system/etc/tfa/fm.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/fm_l.drc:system/etc/tfa/fm_l.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/fm_l.eq:system/etc/tfa/fm_l.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/fm_l.preset:system/etc/tfa/fm_l.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/playback.drc:system/etc/tfa/playback.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/playback.eq:system/etc/tfa/playback.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/playback.preset:system/etc/tfa/playback.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackMFG.config:system/etc/tfa/playbackMFG.config \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackMFG.drc:system/etc/tfa/playbackMFG.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackMFG.eq:system/etc/tfa/playbackMFG.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackMFG.preset:system/etc/tfa/playbackMFG.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackMFG_l.config:system/etc/tfa/playbackMFG_l.config \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackMFG_l.drc:system/etc/tfa/playbackMFG_l.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackMFG_l.eq:system/etc/tfa/playbackMFG_l.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackMFG_l.preset:system/etc/tfa/playbackMFG_l.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/playback_l.drc:system/etc/tfa/playback_l.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/playback_l.eq:system/etc/tfa/playback_l.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/playback_l.preset:system/etc/tfa/playback_l.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackwoofer.drc:system/etc/tfa/playbackwoofer.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackwoofer.eq:system/etc/tfa/playbackwoofer.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackwoofer.preset:system/etc/tfa/playbackwoofer.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackwoofer_l.drc:system/etc/tfa/playbackwoofer_l.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackwoofer_l.eq:system/etc/tfa/playbackwoofer_l.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/playbackwoofer_l.preset:system/etc/tfa/playbackwoofer_l.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/tfa9895.config:system/etc/tfa/tfa9895.config \
    vendor/htc/m8qlul/proprietary/etc/tfa/tfa9895.patch:system/etc/tfa/tfa9895.patch \
    vendor/htc/m8qlul/proprietary/etc/tfa/tfa9895.speaker:system/etc/tfa/tfa9895.speaker \
    vendor/htc/m8qlul/proprietary/etc/tfa/tfa9895MFG.patch:system/etc/tfa/tfa9895MFG.patch \
    vendor/htc/m8qlul/proprietary/etc/tfa/tfa9895_l.speaker:system/etc/tfa/tfa9895_l.speaker \
    vendor/htc/m8qlul/proprietary/etc/tfa/voice.drc:system/etc/tfa/voice.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/voice.eq:system/etc/tfa/voice.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/voice.preset:system/etc/tfa/voice.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/voiceWB.eq:system/etc/tfa/voiceWB.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/voiceWB_l.eq:system/etc/tfa/voiceWB_l.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/voice_l.drc:system/etc/tfa/voice_l.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/voice_l.eq:system/etc/tfa/voice_l.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/voice_l.preset:system/etc/tfa/voice_l.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/voip.drc:system/etc/tfa/voip.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/voip.eq:system/etc/tfa/voip.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/voip.preset:system/etc/tfa/voip.preset \
    vendor/htc/m8qlul/proprietary/etc/tfa/voip_l.drc:system/etc/tfa/voip_l.drc \
    vendor/htc/m8qlul/proprietary/etc/tfa/voip_l.eq:system/etc/tfa/voip_l.eq \
    vendor/htc/m8qlul/proprietary/etc/tfa/voip_l.preset:system/etc/tfa/voip_l.preset \
    vendor/htc/m8qlul/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/htc/m8qlul/proprietary/lib/drm/libhtcomaplugin.so:system/lib/drm/libhtcomaplugin.so \
    vendor/htc/m8qlul/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.msm8916.so \
    vendor/htc/m8qlul/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/htc/m8qlul/proprietary/lib/hw/power.htc.so:system/lib/hw/power.htc.so \
    vendor/htc/m8qlul/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so \
    vendor/htc/m8qlul/proprietary/lib/libBeautyChat.so:system/lib/libBeautyChat.so \
    vendor/htc/m8qlul/proprietary/lib/libalDE.so:system/lib/libalDE.so \
    vendor/htc/m8qlul/proprietary/lib/libalDynamicWarping.so:system/lib/libalDynamicWarping.so \
    vendor/htc/m8qlul/proprietary/lib/libalIAF.so:system/lib/libalIAF.so \
    vendor/htc/m8qlul/proprietary/lib/libawb_calibration.so:system/lib/libawb_calibration.so \
    vendor/htc/m8qlul/proprietary/lib/libcamera_aec.so:system/lib/libcamera_aec.so \
    vendor/htc/m8qlul/proprietary/lib/libcamera_af.so:system/lib/libcamera_af.so \
    vendor/htc/m8qlul/proprietary/lib/libcamera_awb.so:system/lib/libcamera_awb.so \
    vendor/htc/m8qlul/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/htc/m8qlul/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
    vendor/htc/m8qlul/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
    vendor/htc/m8qlul/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/htc/m8qlul/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/htc/m8qlul/proprietary/lib/libhtc_depthmap.so:system/lib/libhtc_depthmap.so \
    vendor/htc/m8qlul/proprietary/lib/libhtc_framework.so:system/lib/libhtc_framework.so \
    vendor/htc/m8qlul/proprietary/lib/libhtc_loglevel.so:system/lib/libhtc_loglevel.so \
    vendor/htc/m8qlul/proprietary/lib/libhtc_rilhook.so:system/lib/libhtc_rilhook.so \
    vendor/htc/m8qlul/proprietary/lib/libhtc_ufocusprocess.so:system/lib/libhtc_ufocusprocess.so \
    vendor/htc/m8qlul/proprietary/lib/libhtcdrm1.so:system/lib/libhtcdrm1.so \
    vendor/htc/m8qlul/proprietary/lib/libhtcflag-jni.so:system/lib/libhtcflag-jni.so \
    vendor/htc/m8qlul/proprietary/lib/libhtcqxdm2sd.so:system/lib/libhtcqxdm2sd.so \
    vendor/htc/m8qlul/proprietary/lib/libhtcsecure.so:system/lib/libhtcsecure.so \
    vendor/htc/m8qlul/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/htc/m8qlul/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/htc/m8qlul/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/htc/m8qlul/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/htc/m8qlul/proprietary/lib/libmmcamera_ait9882proc.so:system/lib/libmmcamera_ait9882proc.so \
    vendor/htc/m8qlul/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/htc/m8qlul/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/htc/m8qlul/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
    vendor/htc/m8qlul/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/htc/m8qlul/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/htc/m8qlul/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec.so:system/lib/libtuning_aec.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_hdr.so:system/lib/libtuning_aec_imx214_htc_hdr.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_hdr_16_9.so:system/lib/libtuning_aec_imx214_htc_hdr_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_night.so:system/lib/libtuning_aec_imx214_htc_night.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_night_16_9.so:system/lib/libtuning_aec_imx214_htc_night_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_qtr.so:system/lib/libtuning_aec_imx214_htc_qtr.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_qtr_16_9.so:system/lib/libtuning_aec_imx214_htc_qtr_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_video.so:system/lib/libtuning_aec_imx214_htc_video.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_videoHFR.so:system/lib/libtuning_aec_imx214_htc_videoHFR.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_video_24fps.so:system/lib/libtuning_aec_imx214_htc_video_24fps.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_video_60fps.so:system/lib/libtuning_aec_imx214_htc_video_60fps.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_zoe.so:system/lib/libtuning_aec_imx214_htc_zoe.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_zsl.so:system/lib/libtuning_aec_imx214_htc_zsl.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_zsl_16_9.so:system/lib/libtuning_aec_imx214_htc_zsl_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_zsl_24fps.so:system/lib/libtuning_aec_imx214_htc_zsl_24fps.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_imx214_htc_zsl_24fps_16_9.so:system/lib/libtuning_aec_imx214_htc_zsl_24fps_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_hdr.so:system/lib/libtuning_aec_s5k5e_htc_hdr.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_hdr_16_9.so:system/lib/libtuning_aec_s5k5e_htc_hdr_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_night.so:system/lib/libtuning_aec_s5k5e_htc_night.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_night_16_9.so:system/lib/libtuning_aec_s5k5e_htc_night_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_qtr.so:system/lib/libtuning_aec_s5k5e_htc_qtr.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_qtr_16_9.so:system/lib/libtuning_aec_s5k5e_htc_qtr_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_video.so:system/lib/libtuning_aec_s5k5e_htc_video.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_zsl.so:system/lib/libtuning_aec_s5k5e_htc_zsl.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_aec_s5k5e_htc_zsl_16_9.so:system/lib/libtuning_aec_s5k5e_htc_zsl_16_9.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_af.so:system/lib/libtuning_af.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_af_lc898212_imx214.so:system/lib/libtuning_af_lc898212_imx214.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_awb.so:system/lib/libtuning_awb.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_awb_imx214_htc.so:system/lib/libtuning_awb_imx214_htc.so \
    vendor/htc/m8qlul/proprietary/lib/libtuning_awb_s5k5e_htc.so:system/lib/libtuning_awb_s5k5e_htc.so \
    vendor/htc/m8qlul/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
    vendor/htc/m8qlul/proprietary/lib64/hw/sensors.msm8916.so:system/lib64/hw/sensors.msm8916.so \
    vendor/htc/m8qlul/proprietary/lib64/libawb_calibration.so:system/lib64/libawb_calibration.so \
    vendor/htc/m8qlul/proprietary/lib64/libcamera_aec.so:system/lib64/libcamera_aec.so \
    vendor/htc/m8qlul/proprietary/lib64/libcamera_af.so:system/lib64/libcamera_af.so \
    vendor/htc/m8qlul/proprietary/lib64/libcamera_awb.so:system/lib64/libcamera_awb.so \
    vendor/htc/m8qlul/proprietary/lib64/libcamera_client.so:system/lib64/libcamera_client.so \
    vendor/htc/m8qlul/proprietary/lib64/libgps.utils.so:system/lib64/libgps.utils.so \
    vendor/htc/m8qlul/proprietary/lib64/libhtc_rilhook.so:system/lib64/libhtc_rilhook.so \
    vendor/htc/m8qlul/proprietary/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so \
    vendor/htc/m8qlul/proprietary/lib64/libloc_core.so:system/lib64/libloc_core.so \
    vendor/htc/m8qlul/proprietary/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so \
    vendor/htc/m8qlul/proprietary/lib64/libloc_eng.so:system/lib64/libloc_eng.so \
    vendor/htc/m8qlul/proprietary/lib64/libposteffect.so:system/lib64/libposteffect.so \
    vendor/htc/m8qlul/proprietary/lib64/libril.so:system/lib64/libril.so \
    vendor/htc/m8qlul/proprietary/lib64/librilutils.so:system/lib64/librilutils.so \
    vendor/htc/m8qlul/proprietary/lib64/libtuning_aec.so:system/lib64/libtuning_aec.so \
    vendor/htc/m8qlul/proprietary/lib64/libtuning_af.so:system/lib64/libtuning_af.so \
    vendor/htc/m8qlul/proprietary/lib64/libtuning_af_lc898212_imx214.so:system/lib64/libtuning_af_lc898212_imx214.so \
    vendor/htc/m8qlul/proprietary/lib64/libtuning_awb.so:system/lib64/libtuning_awb.so \
    vendor/htc/m8qlul/proprietary/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp \
    vendor/htc/m8qlul/proprietary/vendor/firmware/keymaster.b00:system/vendor/firmware/keymaster.b00 \
    vendor/htc/m8qlul/proprietary/vendor/firmware/keymaster.b01:system/vendor/firmware/keymaster.b01 \
    vendor/htc/m8qlul/proprietary/vendor/firmware/keymaster.b02:system/vendor/firmware/keymaster.b02 \
    vendor/htc/m8qlul/proprietary/vendor/firmware/keymaster.b03:system/vendor/firmware/keymaster.b03 \
    vendor/htc/m8qlul/proprietary/vendor/firmware/keymaster.mdt:system/vendor/firmware/keymaster.mdt \
    vendor/htc/m8qlul/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/lib-rcsimssjni.so:systemvendor/lib/lib-rcsimssjni.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/lib-rcsjni.so:systemvendor/lib/lib-rcsjni.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/lib-rtpcommon.so:systemvendor/lib/lib-rtpcommon.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/lib-rtpcore.so:systemvendor/lib/lib-rtpcore.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/lib-rtpdaemoninterface.so:systemvendor/lib/lib-rtpdaemoninterface.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/lib-rtpsl.so:systemvendor/lib/lib-rtpsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_a3907.so:system/vendor/lib/libactuator_a3907.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_a3907_camcorder.so:system/vendor/lib/libactuator_a3907_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_a3907_camera.so:system/vendor/lib/libactuator_a3907_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_q13n04a.so:system/vendor/lib/libactuator_dw9714_q13n04a.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so:system/vendor/lib/libactuator_dw9714_q13n04a_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_q13n04a_camera.so:system/vendor/lib/libactuator_dw9714_q13n04a_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_q13v04b.so:system/vendor/lib/libactuator_dw9714_q13v04b.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so:system/vendor/lib/libactuator_dw9714_q13v04b_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9714_q13v04b_camera.so:system/vendor/lib/libactuator_dw9714_q13v04b_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9716.so:system/vendor/lib/libactuator_dw9716.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9716_camcorder.so:system/vendor/lib/libactuator_dw9716_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_dw9716_camera.so:system/vendor/lib/libactuator_dw9716_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_iu074.so:system/vendor/lib/libactuator_iu074.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_iu074_camcorder.so:system/vendor/lib/libactuator_iu074_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_iu074_camera.so:system/vendor/lib/libactuator_iu074_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_lc898212_act.so:system/vendor/lib/libactuator_lc898212_act.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_lc898212_act_camcorder.so:system/vendor/lib/libactuator_lc898212_act_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_lc898212_act_camera.so:system/vendor/lib/libactuator_lc898212_act_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_ov12830.so:system/vendor/lib/libactuator_ov12830.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_ov12830_camcorder.so:system/vendor/lib/libactuator_ov12830_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_ov12830_camera.so:system/vendor/lib/libactuator_ov12830_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_ov8825.so:system/vendor/lib/libactuator_ov8825.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_ov8825_camcorder.so:system/vendor/lib/libactuator_ov8825_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_ov8825_camera.so:system/vendor/lib/libactuator_ov8825_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_120fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_60fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_90fps.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_video_hd.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_S5K4E1_13P1BA_zsl.so:system/vendor/lib/libchromatix_S5K4E1_13P1BA_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx134_hfr_120.so:system/vendor/lib/libchromatix_imx134_hfr_120.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx134_hfr_60.so:system/vendor/lib/libchromatix_imx134_hfr_60.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_common.so:system/vendor/lib/libchromatix_imx214_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_default_video.so:system/vendor/lib/libchromatix_imx214_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_hfr_120fps.so:system/vendor/lib/libchromatix_imx214_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_hfr_60fps.so:system/vendor/lib/libchromatix_imx214_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_hfr_90fps.so:system/vendor/lib/libchromatix_imx214_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_htc_common.so:system/vendor/lib/libchromatix_imx214_htc_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_htc_default_video.so:system/vendor/lib/libchromatix_imx214_htc_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_htc_hfr.so:system/vendor/lib/libchromatix_imx214_htc_hfr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_htc_hfr_60fps.so:system/vendor/lib/libchromatix_imx214_htc_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_htc_preview.so:system/vendor/lib/libchromatix_imx214_htc_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_htc_preview_24fps.so:system/vendor/lib/libchromatix_imx214_htc_preview_24fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_htc_video_24fps.so:system/vendor/lib/libchromatix_imx214_htc_video_24fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_liveshot.so:system/vendor/lib/libchromatix_imx214_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_preview.so:system/vendor/lib/libchromatix_imx214_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_snapshot.so:system/vendor/lib/libchromatix_imx214_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib/libchromatix_imx214_snapshot_hdr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_imx214_video_hdr.so:system/vendor/lib/libchromatix_imx214_video_hdr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov13850_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov13850_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov13850_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov13850_snapshot.so:system/vendor/lib/libchromatix_ov13850_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov16825_common.so:system/vendor/lib/libchromatix_ov16825_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov16825_default_video.so:system/vendor/lib/libchromatix_ov16825_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov16825_preview.so:system/vendor/lib/libchromatix_ov16825_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov16825_snapshot.so:system/vendor/lib/libchromatix_ov16825_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_common.so:system/vendor/lib/libchromatix_ov2680_5987fhq_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so:system/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_preview.so:system/vendor/lib/libchromatix_ov2680_5987fhq_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so:system/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2680_common.so:system/vendor/lib/libchromatix_ov2680_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2680_default_video.so:system/vendor/lib/libchromatix_ov2680_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2680_preview.so:system/vendor/lib/libchromatix_ov2680_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2680_snapshot.so:system/vendor/lib/libchromatix_ov2680_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_common.so:system/vendor/lib/libchromatix_ov5648_p5v18g_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_p5v18g_default_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_preview.so:system/vendor/lib/libchromatix_ov5648_p5v18g_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so:system/vendor/lib/libchromatix_ov5648_p5v18g_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_p5v18g_zsl.so:system/vendor/lib/libchromatix_ov5648_p5v18g_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_common.so:system/vendor/lib/libchromatix_ov5648_q5v22e_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_q5v22e_default_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_preview.so:system/vendor/lib/libchromatix_ov5648_q5v22e_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so:system/vendor/lib/libchromatix_ov5648_q5v22e_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so:system/vendor/lib/libchromatix_ov5648_q5v22e_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8825_zsl.so:system/vendor/lib/libchromatix_ov8825_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_common.so:system/vendor/lib/libchromatix_ov8858_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_default_video.so:system/vendor/lib/libchromatix_ov8858_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_liveshot.so:system/vendor/lib/libchromatix_ov8858_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_preview.so:system/vendor/lib/libchromatix_ov8858_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_common.so:system/vendor/lib/libchromatix_ov8858_q8v19w_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_default_video.so:system/vendor/lib/libchromatix_ov8858_q8v19w_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_q8v19w_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_liveshot.so:system/vendor/lib/libchromatix_ov8858_q8v19w_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_preview.so:system/vendor/lib/libchromatix_ov8858_q8v19w_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_snapshot.so:system/vendor/lib/libchromatix_ov8858_q8v19w_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_zsl.so:system/vendor/lib/libchromatix_ov8858_q8v19w_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8858_snapshot.so:system/vendor/lib/libchromatix_ov8858_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k5e_htc_common.so:system/vendor/lib/libchromatix_s5k5e_htc_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k5e_htc_default_video.so:system/vendor/lib/libchromatix_s5k5e_htc_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k5e_htc_hfr.so:system/vendor/lib/libchromatix_s5k5e_htc_hfr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_s5k5e_htc_preview.so:system/vendor/lib/libchromatix_s5k5e_htc_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_S5K4E1_13P1BA.so:system/vendor/lib/libmmcamera_S5K4E1_13P1BA.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_imx214_htc.so:system/vendor/lib/libmmcamera_imx214_htc.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov16825.so:system/vendor/lib/libmmcamera_ov16825.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov2680.so:system/vendor/lib/libmmcamera_ov2680.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov2680_5987fhq.so:system/vendor/lib/libmmcamera_ov2680_5987fhq.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov2722_yuv.so:system/vendor/lib/libmmcamera_ov2722_yuv.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov5645.so:system/vendor/lib/libmmcamera_ov5645.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov5648_p5v18g.so:system/vendor/lib/libmmcamera_ov5648_p5v18g.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov5648_q5v22e.so:system/vendor/lib/libmmcamera_ov5648_q5v22e.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov7695.so:system/vendor/lib/libmmcamera_ov7695.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov8858.so:system/vendor/lib/libmmcamera_ov8858.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov8858_q8v19w.so:system/vendor/lib/libmmcamera_ov8858_q8v19w.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_s5k5e_htc.so:system/vendor/lib/libmmcamera_s5k5e_htc.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_s5k5e_yuv.so:system/vendor/lib/libmmcamera_s5k5e_yuv.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_sonyimx135_eeprom.so:system/vendor/lib/libmmcamera_sonyimx135_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libscve_mv.so:system/vendor/lib/libscve_mv.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/htc/m8qlul/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/lib-rcsimssjni.so:systemvendor/lib64/lib-rcsimssjni.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/lib-rcsjni.so:systemvendor/lib64/lib-rcsjni.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/lib-rtpcommon.so:systemvendor/lib64/lib-rtpcommon.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/lib-rtpcore.so:systemvendor/lib64/lib-rtpcore.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/lib-rtpdaemoninterface.so:systemvendor/lib64/lib-rtpdaemoninterface.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/lib-rtpsl.so:systemvendor/lib64/lib-rtpsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libFlacSwDec.so:system/vendor/lib64/libFlacSwDec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libacdbmapper.so:system/vendor/lib64/libacdbmapper.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libc2d30-a3xx.so:system/vendor/lib64/libc2d30-a3xx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_common.so:system/vendor/lib64/libchromatix_imx214_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_default_video.so:system/vendor/lib64/libchromatix_imx214_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_hfr_120fps.so:system/vendor/lib64/libchromatix_imx214_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_hfr_60fps.so:system/vendor/lib64/libchromatix_imx214_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_hfr_90fps.so:system/vendor/lib64/libchromatix_imx214_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_htc_common.so:system/vendor/lib64/libchromatix_imx214_htc_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_htc_default_video.so:system/vendor/lib64/libchromatix_imx214_htc_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_htc_hfr.so:system/vendor/lib64/libchromatix_imx214_htc_hfr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_htc_hfr_60fps.so:system/vendor/lib64/libchromatix_imx214_htc_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_htc_preview.so:system/vendor/lib64/libchromatix_imx214_htc_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_htc_preview_24fps.so:system/vendor/lib64/libchromatix_imx214_htc_preview_24fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_htc_video_24fps.so:system/vendor/lib64/libchromatix_imx214_htc_video_24fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_liveshot.so:system/vendor/lib64/libchromatix_imx214_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_preview.so:system/vendor/lib64/libchromatix_imx214_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_snapshot.so:system/vendor/lib64/libchromatix_imx214_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib64/libchromatix_imx214_snapshot_hdr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_imx214_video_hdr.so:system/vendor/lib64/libchromatix_imx214_video_hdr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov13850_default_video.so:system/vendor/lib64/libchromatix_ov13850_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov16825_common.so:system/vendor/lib64/libchromatix_ov16825_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov16825_default_video.so:system/vendor/lib64/libchromatix_ov16825_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov16825_preview.so:system/vendor/lib64/libchromatix_ov16825_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov16825_snapshot.so:system/vendor/lib64/libchromatix_ov16825_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_common.so:system/vendor/lib64/libchromatix_ov8858_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_default_video.so:system/vendor/lib64/libchromatix_ov8858_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_hfr_120fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_hfr_60fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_hfr_90fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_liveshot.so:system/vendor/lib64/libchromatix_ov8858_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_preview.so:system/vendor/lib64/libchromatix_ov8858_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_common.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_default_video.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_120fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_120fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_60fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_60fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_90fps.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_hfr_90fps.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_liveshot.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_liveshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_preview.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_snapshot.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_q8v19w_zsl.so:system/vendor/lib64/libchromatix_ov8858_q8v19w_zsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_ov8858_snapshot.so:system/vendor/lib64/libchromatix_ov8858_snapshot.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_s5k5e_htc_common.so:system/vendor/lib64/libchromatix_s5k5e_htc_common.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_s5k5e_htc_default_video.so:system/vendor/lib64/libchromatix_s5k5e_htc_default_video.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_s5k5e_htc_hfr.so:system/vendor/lib64/libchromatix_s5k5e_htc_hfr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libchromatix_s5k5e_htc_preview.so:system/vendor/lib64/libchromatix_s5k5e_htc_preview.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera2_frame_algorithm.so:system/vendor/lib64/libmmcamera2_frame_algorithm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera2_stats_algorithm.so:system/vendor/lib64/libmmcamera2_stats_algorithm.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_imx214.so:system/vendor/lib64/libmmcamera_imx214.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_imx214_htc.so:system/vendor/lib64/libmmcamera_imx214_htc.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_ov16825.so:system/vendor/lib64/libmmcamera_ov16825.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_ov2722_yuv.so:system/vendor/lib64/libmmcamera_ov2722_yuv.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_ov7695.so:system/vendor/lib64/libmmcamera_ov7695.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_ov8858.so:system/vendor/lib64/libmmcamera_ov8858.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_ov8858_q8v19w.so:system/vendor/lib64/libmmcamera_ov8858_q8v19w.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_s5k5e_htc.so:system/vendor/lib64/libmmcamera_s5k5e_htc.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libmmcamera_s5k5e_yuv.so:system/vendor/lib64/libmmcamera_s5k5e_yuv.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libsc-a2xx.so:system/vendor/lib64/libsc-a2xx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libvendorconn.so:system/vendor/lib64/libvendorconn.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/htc/m8qlul/proprietary/vendor/lib64/mediadrm/libprmediadrmdecrypt.so:system/vendor/lib64/mediadrm/libprmediadrmdecrypt.so

